apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: worker
        image: your-dockerhub-username/python-api:latest
        command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: python-api-config
        - secretRef:
            name: python-api-secrets
